changes in Organization name some validation changes
nhsengland/innovation-service-api pull request #111
Opened 2021-12-30 11:53 UTC by JyotiJaiswal169

2022-01-03 16:43 UTC, assimoes-bjss requested changes
Why not use

2022-01-03 16:43 UTC, assimoes-bjss commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +    const data = [
Why are you not using the `queryRunner` object?
Why using the repo on here? Is there a reason to not write plain T-SQL statements?

2022-01-03 16:43 UTC, assimoes-bjss commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +      orgUnit.name = orgUnitObj.name;
Isn't this updating the the name by exactly the same value? Like...doing nothing?

2022-01-03 16:43 UTC, assimoes-bjss commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +    // const repo = this.getRepository();
How can I revert this?

2022-01-03 16:48 UTC, JyotiJaiswal169 commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +    const data = [
I have used existing seed code and created new seed to update Organization name in database 
This (1627914973606-alter-organisation-units-names.ts
 )seed file to update Organization name was already there

2022-01-03 16:55 UTC, JyotiJaiswal169 commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +      orgUnit.name = orgUnitObj.name;
On local i have tested its updating the name

2022-01-03 17:01 UTC, assimoes-bjss commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +    const data = [
Ok.

2022-01-03 17:01 UTC, assimoes-bjss commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +      orgUnit.name = orgUnitObj.name;
Ok.

2022-01-03 17:02 UTC, assimoes-bjss requested changes

2022-01-03 17:02 UTC, assimoes-bjss commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +    // const repo = this.getRepository();
Given the above comments, there needs to be a way of reverting these changes. Regardless the fact there is a seed file created on the 2nd of August that does not have a revert.

2022-01-03 17:04 UTC, JyotiJaiswal169 commented on __external__/domain/seeds/1640858698485-alter-organisations-units-names.ts
> +    // const repo = this.getRepository();
Okay

2022-01-05 15:22 UTC, assimoes-bjss approved these changes

2022-01-05 16:44 UTC, BJSS-RicardoTavares approved these changes

2022-01-05 16:55 UTC, merged