Additional field for section 1.1
nhsengland/innovation-service-api pull request #117
Opened 2022-01-07 14:35 UTC by JyotiJaiswal169

2022-01-07 15:10 UTC, assimoes-bjss requested changes

2022-01-07 15:10 UTC, assimoes-bjss commented on __external__/domain/src/entity/innovation/Innovation.entity.ts
> +  @Column({ name: "moreSupportDescription", nullable: true })
column names on sql server are snake case.

2022-01-07 15:10 UTC, assimoes-bjss commented on __external__/domain/migrations/1641480958449-alter-innovationtable-add-newcolumn.ts
> +      `ALTER TABLE "innovation" ADD moreSupportDescription nvarchar(500) NULL;`
column names are snake case, not camel case.

2022-01-10 14:26 UTC, assimoes-bjss approved these changes

2022-01-10 16:17 UTC, BJSS-RicardoTavares approved these changes

2022-01-10 16:17 UTC, merged