Feat/user role decorator
nhsengland/innovation-service-api pull request #121
Opened 2022-01-24 12:00 UTC by JyotiJaiswal169

2022-01-24 12:23 UTC, assimoes-bjss requested changes

2022-01-24 12:23 UTC, assimoes-bjss commented on utils/decorators/index.ts
> +export function ServiceRoleValidator(...roles: string[]) {
Create an Enumerator with the possible roles. So instead of an array of string, it takes an array of ServiceRole enumerator values

2022-01-24 15:11 UTC, JyotiJaiswal169 commented on utils/decorators/index.ts
> +export function ServiceRoleValidator(...roles: string[]) {
@assimoes-bjss Please review changes made as per suggestion

2022-01-24 15:15 UTC, assimoes-bjss approved these changes

2022-01-24 15:28 UTC, BJSS-RicardoTavares requested changes

2022-01-24 15:28 UTC, BJSS-RicardoTavares commented on utils/decorators/index.ts
> +export function ServiceRoleValidator(...roles: ServiceRole[]) {
Why is this parameter using the spread operator?

2022-01-25 05:18 UTC, ShaliniNHS approved these changes

2022-01-25 07:06 UTC, merged