Feat/edit comment and reply
nhsengland/innovation-service-api pull request #165
Opened 2022-03-21 17:17 UTC by JyotiJaiswal169

2022-03-21 17:33 UTC, Diogo-Teixeira-BJSS requested changes

2022-03-21 17:33 UTC, Diogo-Teixeira-BJSS commented on __external__/services/src/models/CommentModel.ts
> +  is_editable: boolean;
please change to "isEditable"

2022-03-21 17:33 UTC, Diogo-Teixeira-BJSS commented on __external__/services/src/services/Comment.service.ts
> +      const comment = await this.commentRepo.findOne(id);
find by id and innovation id (to validate if both are correct)

2022-03-21 17:33 UTC, Diogo-Teixeira-BJSS commented on __external__/services/src/services/Comment.service.ts
> +      is_editable: comment.isEditable,
"updatedAt" and "isEditable" please

2022-03-22 08:47 UTC, Diogo-Teixeira-BJSS approved these changes

2022-03-22 09:44 UTC, assimoes-bjss approved these changes

2022-03-22 09:44 UTC, merged