Set editable comments
nhsengland/innovation-service-api pull request #170
Opened 2022-03-24 13:34 UTC by ShaliniNHS

2022-03-24 14:03 UTC, Diogo-Teixeira-BJSS requested changes

2022-03-24 14:03 UTC, Diogo-Teixeira-BJSS commented on __external__/domain/migrations/1648123693511-seed-isEditable-comments.ts
> +    );
this query will miss some innovator & QA records

2022-03-24 15:06 UTC, Diogo-Teixeira-BJSS approved these changes

2022-03-25 07:10 UTC, JyotiJaiswal169 approved these changes

2022-03-25 07:10 UTC, merged