add logic to service and update model
nhsengland/innovation-service-api pull request #228
Opened 2022-05-23 13:08 UTC by Pedro-Lemos-BJSS

- calling /me endpoint now returns if the user has accepted the last terms of use or not

2022-05-23 13:57 UTC, assimoes-bjss requested changes

2022-05-23 13:57 UTC, assimoes-bjss commented on __external__/services/src/services/User.service.ts
> +          userDb.type === UserType.ADMIN
This should be checked right off the bat. If the user is an Admin, you can assume the ToU is accepted and therefore no longer need to do 2 database calls.

2022-05-25 13:31 UTC, assimoes-bjss approved these changes

2022-05-25 14:38 UTC, JyotiJaiswal169 approved these changes

2022-05-25 14:38 UTC, merged